name: Trigger auto deployment for capps-backend-bzbvhtgprsg5c

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capps-backend-bzbvhtgprsg5c-AutoDeployTrigger-74ad687d-848d-4d94-82ad-8d5e7d594578.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAPPSBACKENDBZBVHTGPRSG5C_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPSBACKENDBZBVHTGPRSG5C_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPSBACKENDBZBVHTGPRSG5C_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ragatsmainacrntlvzrqzr2jis.azurecr.io
          registryUsername: ${{ secrets.CAPPSBACKENDBZBVHTGPRSG5C_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSBACKENDBZBVHTGPRSG5C_REGISTRY_PASSWORD }}
          containerAppName: capps-backend-bzbvhtgprsg5c
          resourceGroup: rg-AzureRAGDev
          imageToBuild: ragatsmainacrntlvzrqzr2jis.azurecr.io/capps-backend-bzbvhtgprsg5c:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


